variable "resource_name" {}
variable "subscription-id" {}
variable "client-id" {}
variable "client-secret" {}
variable "tenant-id" {}
variable "registry_username" {}
variable "registry_password" {}
variable "dnsimple_auth_token" {}
variable "dnsimple_account" {}
variable "domain" {}
variable "email" {}