variable "resource_name" {}
variable "subscriptionid" {}
variable "clientid" {}
variable "clientsecret" {}
variable "tenantid" {}
variable "registry_username" {}
variable "registry_password" {}
variable "dnsimple_auth_token" {}
variable "dnsimple_account" {}
variable "domain" {}
variable "email" {}