variable "resource_name" {}
variable "subscription_id" {}
variable "client_id" {}
variable "client_secret" {}
variable "tenant_id" {}
variable "registry_username" {}
variable "registry_password" {}
variable "dnsimple_auth_token" {}
variable "dnsimple_account" {}
variable "domain" {}
variable "email" {}
variable "hostname" {}