name: validate

on: [push]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Test
      run: dotnet test src/ImageProcessor.sln
    - name: Build
      run: dotnet publish src/ImageProcessor/ImageProcessor.csproj --configuration Release
